# docker-compose.yml
version: "3.7"
services:
    app-backend:
        container_name: app-healthcheck
        build: .
        network_mode: "host"
        environment:
            - INSTANCE_NAME=${INSTANCE_NAME}
