# docker-compose.yml
version: "3.7"
services:
    app-frontend:
        container_name: app-frontend
        build: .
        ports:
            - "80:3000"
        environment:
            - INSTANCE_NAME=${INSTANCE_NAME}
            - PRIVATE_IP=${PRIVATE_IP}
