"""model change

Revision ID: 643e85be2728
Revises: 
Create Date: 2023-04-30 00:10:47.380124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643e85be2728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
